name: Trivial Checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: { }

jobs:
  fake:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - run: sleep 7
      - run: echo "Success"
